
# Step 1

FROM node:latest as build-step

RUN mkdir /app

WORKDIR /app

COPY package.json /app

RUN npm install
# RUN npm audit fix --force

COPY . /app

RUN npm run build


# Stage 2

FROM nginx:1.17.1-alpine

WORKDIR /var/www

COPY --from=build-step /app/build .
COPY --from=build-step /app/nginx.conf /etc/nginx/nginx.conf

COPY ./env.sh .

RUN apk add --no-cache bash

RUN chmod +x env.sh
#/bin/bash -c /var/www/env.sh /mnt/config && nginx -g "daemon off;"
CMD ["/bin/bash", "-c", "/var/www/env.sh /mnt/config && nginx -g \"daemon off;\""]